{% set name = "gctree" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gctree-{{ version }}.tar.gz
  sha256: 271bd14bf42a58cfbb5e0c998bed4c41940c09be4c3afc9baefc725732493702

build:
  entry_points:
    - gctree=gctree.cli:main
    - deduplicate=gctree.deduplicate:main
    - mkconfig=gctree.mkconfig:main
    - isotype=gctree.isotype:main
    - phylip_parse=gctree.phylip_parse:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - biopython
    - ete3
    - frozendict
    - historydag >=1.2.0
    - matplotlib-base
    - multiset
    - pandas
    - pyqt
    - python >=3.7,<3.10
    - scipy
    - seaborn

test:
  imports:
    - gctree
  commands:
    - pip check
    - gctree --help
    - deduplicate --help
    - mkconfig --help
    - isotype --help
    - phylip_parse --help
  requires:
    - pip

about:
  home: https://matsengrp.github.io/gctree
  summary: phylogenetic inference of genotype-collapsed trees
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  description: |
    gctree is a command line utility and Python package for using
    sequence abundance information in phylogenetic inference.
  doc_url: https://matsengrp.github.io/gctree
  dev_url: https://github.com/matsengrp/gctree

extra:
  recipe-maintainers:
    - WSDeWitt
    - willdumm
